#!/usr/bin/bash
yum -y install vim
yum -y install tcl
yum -y install expect
yum -y install graphviz
ln -s /sys/kernel/debug /debug
chmod +x disk_init
chmod +x ftrace2
#./disk_init
cd mypvtrace
make install
make clean
